### PR TITLE
Added Quiz App

### PR DESCRIPTION
**Pull request by dubey2709**
Added a quiz app made using flutter

### CODE REVIEW

**Comment by SR-Sunny-Raj** [comment]
Hey, Can you explain how one can see your files as it shows submodule which doesn't opens.

**Comment by dubey2709** [comment]
So sir what should I do now?

**Comment by dubey2709** [comment]
Am I doing any mistake

**Comment by SR-Sunny-Raj** [comment]
> Am I doing any mistake

try uploading your files manually. As the contents of your folder are not visible.

**Pull request closed without merging**
