### PR TITLE
Added my comment app

### PR DESCRIPTION
**Pull request by AryanSahoo-2003**
Hey!!I made my Comment Application Website using basic php and html!!
my interface looks like this..
image
Please confirm it under Hacktoberfest accepted label

### CODE REVIEW

**Review by SR-Sunny-Raj — APPROVED** [review]
Great Work. Keep it up 👍🏻and please don't forget to star this repository.

**Comment by AryanSahoo-2003** [comment]
Sure sir!!If possible..pls send me a notification if any such fun event happens again!! :)

**Comment by AryanSahoo-2003** [comment]
Hello Sir !! Why has your repo again excluded?Sorry if I am being rude but it actually wasted a lot of time (3 days) and thus I don't think I will be in top 40 k this year as my 4th commit got excluded...Can you do something about this?As I think it is issue from your side!!!
Please reply fast>>

**Comment by SR-Sunny-Raj** [comment]
It happened because this repository was getting a huge number of pull requests so the hacktoberfest team excluded it. Sorry to say but I can't do anything in this. Anyways contribution to open source and learning matters more than any swags. Also please try to make more than 4 PR's in different repositories over github in order to increase your chances to complete the hacktoberfest.
Also don't worry there's still a lot of time left for you to make your contribution and definitely you will be in the top 40k contributors. 
Happy hacking👍🏻

**Pull request merged**
